INSERT INTO TODO (ID, USERNAME, DESCRIPTION, TARGET_DATE, DONE)
VALUES(10001, 'in28minutes', 'Learn Spring', CURRENT_DATE(), false);

INSERT INTO TODO (ID, USERNAME, DESCRIPTION, TARGET_DATE, DONE)
VALUES(10002, 'in28minutes', 'Learn Java', CURRENT_DATE(), false);

INSERT INTO TODO (ID, USERNAME, DESCRIPTION, TARGET_DATE, DONE)
VALUES(10003, 'in28minutes', 'Learn ReactJS', CURRENT_DATE(), false);

INSERT INTO TODO (ID, USERNAME, DESCRIPTION, TARGET_DATE, DONE)
VALUES(10004, 'in28minutes', 'Learn Typescript', CURRENT_DATE(), false);